export const metadata = {
  title: {
    default: "next.js Tutorial - surya",
    template: "%s | surya",
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
       <h1 style={{backgroundColor: 'lightblue', alignItems: 'center', justifyContent: 'center'}}> Header</h1>
        {children}
       <h1 style={{backgroundColor: 'lightgreen'}}>Footer</h1>
      </body>
    </html>
  )
}
